import type { Question } from "@/types"

export const LEVEL_TEST_QUESTIONS: Question[] = [
  // ── 관계사 ──────────────────────────────────────────────
  {
    id: 1,
    type: "관계사",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "The scientist _____ research changed our understanding of DNA won the Nobel Prize.",
    options: ["(A) who", "(B) whose", "(C) whom", "(D) which"],
    answer: "(B) whose",
    explanation: "빈칸 뒤에 명사 'research'가 이어지므로 소유격 관계대명사 whose가 필요합니다. who/whom은 주격·목적격으로 뒤에 바로 동사나 목적어가 옵니다.",
    trap: "research 앞에 빈칸이 있어 주격 who를 선택하기 쉽지만, 'whose research'는 '그의 연구'라는 소유 관계입니다.",
    difficulty: "중급",
    subType: "소유격 관계대명사 whose",
    discriminationPower: "상",
    commonMistake: "whose 뒤에 명사가 오는 구조를 인식하지 못하고 주격 who를 선택",
    relatedPart: ["수일치"],
    studyDays: 3,
  },
  {
    id: 2,
    type: "관계사",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "This is the building _____ the historic treaty was signed in 1945.",
    options: ["(A) which", "(B) that", "(C) where", "(D) when"],
    answer: "(C) where",
    explanation: "선행사 'building'은 장소이고, 관계절 안에 주어(the treaty)·동사(was signed)·부사구(in 1945)가 모두 갖춰져 있어 장소 관계부사 where가 적절합니다.",
    trap: "which/that는 관계대명사로 절 안에 빠진 명사 역할이 있어야 하는데, 이 절은 완전한 문장이므로 관계부사를 써야 합니다.",
    difficulty: "중급",
    subType: "관계부사 where — 완전한 절 판별",
    discriminationPower: "상",
    commonMistake: "선행사가 장소라도 관계절이 완전한 문장이면 관계부사를 써야 하는데 관계대명사 which를 선택",
    relatedPart: ["시제"],
    studyDays: 3,
  },
  {
    id: 3,
    type: "관계사",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "She recommended several books, _____ I found particularly helpful for the exam.",
    options: ["(A) that", "(B) which", "(C) what", "(D) whom"],
    answer: "(B) which",
    explanation: "선행사가 'several books'(사물)이고 콤마 뒤의 계속적 용법이므로 which를 씁니다. 계속적 용법에서는 that을 쓸 수 없습니다.",
    trap: "사물이므로 which와 that 모두 관계대명사로 쓸 수 있을 것 같지만, 콤마가 있는 계속적 용법에서는 반드시 which를 써야 합니다.",
    difficulty: "중급",
    subType: "계속적 용법 which — that 배제",
    discriminationPower: "중",
    commonMistake: "콤마 뒤 계속적 용법에서 that을 선택하거나 what과 혼동",
    relatedPart: ["병렬구조"],
    studyDays: 2,
  },
  {
    id: 4,
    type: "관계사",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "The reason _____ he resigned is still unknown to the public.",
    options: ["(A) why", "(B) which", "(C) that", "(D) for that"],
    answer: "(A) why",
    explanation: "선행사 'reason' 뒤에는 관계부사 why를 씁니다. 'the reason why S+V'는 '~한 이유'를 나타내는 표현입니다.",
    trap: "that도 reason 뒤에 쓸 수 있지만(the reason that), 이 문장에서는 why가 더 자연스럽고 관계부사 패턴을 묻는 문제입니다.",
    difficulty: "중급",
    subType: "관계부사 why — reason 선행사",
    discriminationPower: "중",
    commonMistake: "reason 뒤에 which나 that을 선택해 관계대명사 문법으로 접근",
    relatedPart: ["시제"],
    studyDays: 2,
  },

  // ── 분사구문 ─────────────────────────────────────────────
  {
    id: 5,
    type: "분사구문",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "_____ from the top of the hill, the entire city looked breathtaking.",
    options: ["(A) Seen", "(B) Seeing", "(C) Having see", "(D) To see"],
    answer: "(A) Seen",
    explanation: "주절의 주어 'the city'가 분사구문의 의미상 주어인데, 도시는 '보이는' 것(수동)이므로 과거분사 Seen이 맞습니다.",
    trap: "Seeing을 선택하면 '도시가 바라보는' 능동의 의미가 되어 문맥상 어색합니다.",
    difficulty: "중급",
    subType: "수동 분사구문 — 과거분사",
    discriminationPower: "상",
    commonMistake: "주절 주어와 분사구문의 능동/수동 관계를 혼동해 현재분사 Seeing 선택",
    relatedPart: ["수일치"],
    studyDays: 4,
  },
  {
    id: 6,
    type: "분사구문",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "_____ his homework, he went out to play with his friends.",
    options: ["(A) Finishing", "(B) Having finished", "(C) Finished", "(D) Being finished"],
    answer: "(B) Having finished",
    explanation: "분사구문의 동작(숙제 완료)이 주절의 동작(나가서 놀기)보다 먼저 일어났으므로 완료 분사구문 Having finished를 씁니다.",
    trap: "Finishing을 쓰면 두 동작이 동시에 일어나는 것처럼 보여 의미상 어색합니다.",
    difficulty: "중급",
    subType: "완료 분사구문 Having p.p.",
    discriminationPower: "상",
    commonMistake: "시간 선후 관계를 무시하고 단순 현재분사 Finishing 선택",
    relatedPart: ["시제"],
    studyDays: 4,
  },
  {
    id: 7,
    type: "분사구문",
    question: "밑줄 친 부분 중 어법상 틀린 것을 고르시오.",
    sentence: "Not knowing what to do, (A) the problem (B) was (C) left (D) unsolved by the committee.",
    options: ["(A)", "(B)", "(C)", "(D)"],
    answer: "(A)",
    explanation: "분사구문 'Not knowing what to do'의 의미상 주어는 주절의 주어와 일치해야 합니다. 주절의 주어가 'the problem'이면 '문제가 모른다'는 어색한 의미가 됩니다. 주절을 'the committee left the problem unsolved'로 고쳐야 합니다.",
    trap: "수동태 문장 자체는 문법적으로 맞지만, 분사구문의 의미상 주어와 주절 주어의 불일치가 문제입니다.",
    difficulty: "고급",
    subType: "분사구문 의미상 주어 불일치 (dangling modifier)",
    discriminationPower: "상",
    commonMistake: "수동태 구문 자체는 맞아 보여 오류를 인식하지 못하고 (D)를 선택",
    relatedPart: ["수일치", "병렬구조"],
    studyDays: 5,
  },
  {
    id: 8,
    type: "분사구문",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "_____ in a small town, she had always dreamed of moving to a big city.",
    options: ["(A) Grown up", "(B) Having grown up", "(C) Growing up", "(D) Being grown up"],
    answer: "(B) Having grown up",
    explanation: "자라난 것이 꿈꾼 것보다 시간적으로 앞서므로 완료 분사구문 Having grown up이 적절합니다.",
    trap: "Growing up도 문법적으로 틀리지는 않지만, 성장이 완료된 상태에서 꿈을 꿔왔다는 시간 관계를 정확히 표현하려면 완료형이 필요합니다.",
    difficulty: "중급",
    subType: "완료 분사구문 시제 선택",
    discriminationPower: "중",
    commonMistake: "현재분사 Growing up과 완료분사의 시제 차이를 무시하고 Growing up 선택",
    relatedPart: ["시제"],
    studyDays: 3,
  },

  // ── 가정법 ───────────────────────────────────────────────
  {
    id: 9,
    type: "가정법",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "If I _____ more time yesterday, I would have finished the report.",
    options: ["(A) had had", "(B) have had", "(C) had", "(D) would have had"],
    answer: "(A) had had",
    explanation: "과거 사실의 반대를 나타내는 가정법 과거완료에서 if절은 had+p.p.를 씁니다. 'time'을 '가지다'의 had를 한 번, 완료형 had를 한 번 써서 had had가 됩니다.",
    trap: "had를 하나만 쓰면 가정법 과거(현재 반대)가 되어 'yesterday'와 시제가 맞지 않습니다.",
    difficulty: "중급",
    subType: "가정법 과거완료 if절 — had had",
    discriminationPower: "상",
    commonMistake: "had를 하나만 써서 가정법 과거와 혼동하거나 yesterday를 무시하고 had 선택",
    relatedPart: ["시제"],
    studyDays: 5,
  },
  {
    id: 10,
    type: "가정법",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "Without your help, I _____ the deadline.",
    options: ["(A) cannot meet", "(B) could not have met", "(C) could not meet", "(D) had not met"],
    answer: "(B) could not have met",
    explanation: "'Without your help'는 '네 도움이 없었더라면'의 뜻으로 가정법 과거완료의 조건절 역할을 합니다. 따라서 주절은 could not have met(과거완료)이 됩니다.",
    trap: "could not meet는 가정법 과거(현재·미래 반대)에 쓰이는 표현으로, 과거 사실을 반대로 가정하는 이 문장과 맞지 않습니다.",
    difficulty: "중급",
    subType: "Without 가정법 과거완료",
    discriminationPower: "상",
    commonMistake: "without을 단순 조건으로 해석해 could not meet(현재형) 선택",
    relatedPart: ["시제"],
    studyDays: 4,
  },
  {
    id: 11,
    type: "가정법",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "I wish I _____ the answer to that question during the interview.",
    options: ["(A) knew", "(B) know", "(C) had known", "(D) would know"],
    answer: "(C) had known",
    explanation: "I wish 뒤에서 과거 사실에 대한 아쉬움을 표현할 때는 가정법 과거완료(had p.p.)를 씁니다. 면접 당시에 알았더라면 좋았을 텐데 라는 뜻입니다.",
    trap: "knew는 현재 사실에 대한 아쉬움(I wish I knew → 지금 모른다)을 나타내며, 과거의 면접 상황과 시제가 맞지 않습니다.",
    difficulty: "중급",
    subType: "I wish 가정법 과거/과거완료 구분",
    discriminationPower: "중",
    commonMistake: "I wish 뒤에서 과거(knew)와 과거완료(had known)의 의미 차이를 무시",
    relatedPart: ["시제"],
    studyDays: 4,
  },
  {
    id: 12,
    type: "가정법",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "_____ it not been for the sudden storm, the outdoor concert would have proceeded as planned.",
    options: ["(A) Had", "(B) Were", "(C) Should", "(D) If"],
    answer: "(A) Had",
    explanation: "if를 생략한 가정법 과거완료의 도치 구문입니다. 'Had it not been for ~'는 'If it had not been for ~'(~이 없었더라면)의 도치형입니다.",
    trap: "Were는 가정법 과거의 도치(Were it not for ~)에 쓰이므로, 과거완료 시제인 이 문장에는 맞지 않습니다.",
    difficulty: "고급",
    subType: "가정법 도치 구문 — Had/Were/Should 구분",
    discriminationPower: "상",
    commonMistake: "Had와 Were의 도치 시제 구분을 모르고 Were 선택",
    relatedPart: ["시제"],
    studyDays: 6,
  },

  // ── 시제 ─────────────────────────────────────────────────
  {
    id: 13,
    type: "시제",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "By the time she arrives at the station, the last train _____ already.",
    options: ["(A) will leave", "(B) will have left", "(C) has left", "(D) had left"],
    answer: "(B) will have left",
    explanation: "By the time + 현재시제(arrives)는 미래의 한 시점을 기준으로 합니다. 그 시점보다 먼저 완료될 일은 미래완료(will have p.p.)로 나타냅니다.",
    trap: "had left는 과거완료로, 과거의 기준점보다 앞선 일에 씁니다. 기준점이 미래(arrives)이므로 미래완료가 맞습니다.",
    difficulty: "중급",
    subType: "미래완료 — by the time + 현재형",
    discriminationPower: "상",
    commonMistake: "by the time 뒤 현재형을 과거 기준으로 혼동해 과거완료 had left 선택",
    relatedPart: ["가정법"],
    studyDays: 4,
  },
  {
    id: 14,
    type: "시제",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "The company _____ in this city since it was founded in 1990.",
    options: ["(A) operates", "(B) is operating", "(C) has been operating", "(D) operated"],
    answer: "(C) has been operating",
    explanation: "since 1990으로 과거부터 현재까지 계속 이어지는 동작을 나타내므로 현재완료진행(has been operating)이 적절합니다.",
    trap: "operates(단순현재)는 일반적인 사실·습관을 나타내며, since와 함께 과거부터의 지속을 표현하기 어렵습니다.",
    difficulty: "중급",
    subType: "현재완료진행 — since와 지속 동작",
    discriminationPower: "중",
    commonMistake: "since를 보고도 단순현재 operates를 선택하거나 현재진행과 혼동",
    relatedPart: ["수일치"],
    studyDays: 3,
  },
  {
    id: 15,
    type: "시제",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "She told me that she _____ the project the day before.",
    options: ["(A) completed", "(B) had completed", "(C) has completed", "(D) completes"],
    answer: "(B) had completed",
    explanation: "간접화법에서 주절(told)이 과거이고 종속절의 동작이 그보다 더 앞서 일어났으므로 과거완료(had completed)로 시제를 일치시킵니다.",
    trap: "completed(단순과거)를 쓰면 문법적으로 완전히 틀리지는 않지만, '전날'이라는 시간 관계를 명확히 표현하는 데는 과거완료가 더 정확합니다.",
    difficulty: "중급",
    subType: "시제 일치 — 간접화법 과거완료",
    discriminationPower: "중",
    commonMistake: "간접화법의 시제일치 규칙을 적용하지 않고 단순과거 completed 선택",
    relatedPart: ["가정법"],
    studyDays: 3,
  },
  {
    id: 16,
    type: "시제",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "I _____ him three times today, but he still hasn't replied.",
    options: ["(A) called", "(B) have called", "(C) had called", "(D) was calling"],
    answer: "(B) have called",
    explanation: "today는 아직 끝나지 않은 오늘 하루를 가리키므로 현재완료(have called)를 씁니다. 현재완료는 과거의 행위가 현재와 연결될 때 사용합니다.",
    trap: "called(단순과거)는 명확한 과거 시점 표현(yesterday, last night 등)과 함께 씁니다. today처럼 현재를 포함하는 시간 표현에는 현재완료가 맞습니다.",
    difficulty: "초급",
    subType: "현재완료 vs 단순과거 — today 시간부사",
    discriminationPower: "중",
    commonMistake: "today를 과거 시점으로 혼동해 단순과거 called 선택",
    relatedPart: ["수일치"],
    studyDays: 2,
  },

  // ── 수일치 ───────────────────────────────────────────────
  {
    id: 17,
    type: "수일치",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "Neither the manager nor the employees _____ aware of the new policy.",
    options: ["(A) was", "(B) were", "(C) is", "(D) has been"],
    answer: "(B) were",
    explanation: "neither A nor B 구문에서 동사는 B(employees)에 수를 일치시킵니다. employees는 복수이므로 were가 맞습니다.",
    trap: "neither를 보고 단수로 착각하여 was를 선택하기 쉽습니다. 'neither A nor B' 규칙에서 동사는 항상 B에 일치합니다.",
    difficulty: "중급",
    subType: "neither A nor B — B에 수일치",
    discriminationPower: "상",
    commonMistake: "neither를 보고 단수로 착각해 was 선택, B(employees) 무시",
    relatedPart: ["병렬구조"],
    studyDays: 4,
  },
  {
    id: 18,
    type: "수일치",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "The number of students who fail the exam _____ increasing every year.",
    options: ["(A) are", "(B) is", "(C) were", "(D) have been"],
    answer: "(B) is",
    explanation: "'The number of + 복수명사'는 단수 취급하여 단수 동사를 씁니다. cf. 'A number of + 복수명사'는 '많은'의 의미로 복수 동사를 씁니다.",
    trap: "students(복수)를 보고 are를 선택하기 쉽습니다. 주어는 students가 아니라 'The number'(단수)입니다.",
    difficulty: "중급",
    subType: "The number of vs A number of",
    discriminationPower: "상",
    commonMistake: "of 뒤 복수명사 students를 주어로 착각해 복수 동사 are 선택",
    relatedPart: ["관계사"],
    studyDays: 3,
  },
  {
    id: 19,
    type: "수일치",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "Each of the participants _____ required to submit a written report.",
    options: ["(A) are", "(B) were", "(C) is", "(D) have been"],
    answer: "(C) is",
    explanation: "each, every, either, neither 등은 단수 취급합니다. 'Each of the participants'의 핵심 주어는 each(단수)이므로 is가 맞습니다.",
    trap: "participants(복수)를 보고 are를 고르기 쉽습니다. of the participants는 수식어구일 뿐, 주어는 each입니다.",
    difficulty: "초급",
    subType: "each/every 단수 취급",
    discriminationPower: "중",
    commonMistake: "of the participants의 복수명사를 주어로 혼동해 복수 동사 are 선택",
    relatedPart: ["관계사"],
    studyDays: 2,
  },
  {
    id: 20,
    type: "수일치",
    question: "밑줄 친 부분 중 어법상 틀린 것을 고르시오.",
    sentence: "Not only the students but also the teacher (A) were (B) surprised at (C) how quickly the new system (D) was adopted.",
    options: ["(A)", "(B)", "(C)", "(D)"],
    answer: "(A)",
    explanation: "'Not only A but also B' 구문에서 동사는 B(the teacher)에 수를 일치시킵니다. the teacher는 단수이므로 were가 아닌 was가 맞습니다.",
    trap: "students(복수)가 먼저 나와서 복수 동사 were가 맞다고 착각하기 쉽습니다. 항상 B에 동사를 일치시켜야 합니다.",
    difficulty: "중급",
    subType: "not only A but also B — B에 수일치",
    discriminationPower: "상",
    commonMistake: "A(students, 복수)에 동사를 맞춰 were가 맞다고 판단",
    relatedPart: ["병렬구조"],
    studyDays: 3,
  },

  // ── 병렬구조 ─────────────────────────────────────────────
  {
    id: 21,
    type: "병렬구조",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "The professor asked us to read the article, summarize the main points, and _____ our findings.",
    options: ["(A) presenting", "(B) to present", "(C) presentation of", "(D) present"],
    answer: "(D) present",
    explanation: "and로 연결된 병렬구조에서 앞의 두 항목이 동사원형(read, summarize)이므로 뒤에도 동사원형 present가 와야 합니다.",
    trap: "to present를 선택하면 앞의 read, summarize와 형태가 달라져 병렬이 깨집니다. to부정사 없이 원형만 쓰는 것이 맞습니다.",
    difficulty: "초급",
    subType: "동사원형 병렬 — to부정사 배제",
    discriminationPower: "중",
    commonMistake: "to ask ~ to V 구문을 착각해 to present 선택",
    relatedPart: ["수일치"],
    studyDays: 2,
  },
  {
    id: 22,
    type: "병렬구조",
    question: "밑줄 친 부분 중 어법상 틀린 것을 고르시오.",
    sentence: "She is known for her (A) intelligence, (B) creativity, and (C) being dedicated (D) to her work.",
    options: ["(A)", "(B)", "(C)", "(D)"],
    answer: "(C)",
    explanation: "for 뒤에 intelligence, creativity(명사)가 병렬로 연결되어 있으므로 세 번째 항목도 명사형이 되어야 합니다. 'being dedicated'가 아니라 'dedication'이 맞습니다.",
    trap: "being dedicated 자체는 동명사구로 문법적으로 가능하지만, 앞의 두 명사(intelligence, creativity)와 병렬을 이루려면 명사 dedication을 써야 합니다.",
    difficulty: "중급",
    subType: "명사구 병렬 — 동명사구 vs 명사",
    discriminationPower: "상",
    commonMistake: "동명사구(being dedicated)를 명사와 같은 형태로 인식해 병렬 오류를 놓침",
    relatedPart: ["분사구문"],
    studyDays: 3,
  },
  {
    id: 23,
    type: "병렬구조",
    question: "빈칸에 알맞은 것을 고르시오.",
    sentence: "The new policy will not only reduce costs but also _____ employee productivity.",
    options: ["(A) improving", "(B) to improve", "(C) improvement of", "(D) improve"],
    answer: "(D) improve",
    explanation: "'not only A but also B' 구문에서 A(reduce)가 동사원형이므로 B도 동사원형 improve가 와야 합니다.",
    trap: "to improve를 선택하면 'but also to improve'가 되어 병렬이 깨집니다. not only 뒤의 형태와 but also 뒤의 형태를 반드시 일치시켜야 합니다.",
    difficulty: "초급",
    subType: "not only A but also B 병렬",
    discriminationPower: "중",
    commonMistake: "but also 뒤에 to improve(to부정사) 사용",
    relatedPart: ["수일치"],
    studyDays: 2,
  },
  {
    id: 24,
    type: "병렬구조",
    question: "밑줄 친 부분 중 어법상 틀린 것을 고르시오.",
    sentence: "The report was (A) thorough, (B) well-organized, and (C) it presented the data (D) clearly.",
    options: ["(A)", "(B)", "(C)", "(D)"],
    answer: "(C)",
    explanation: "형용사 thorough, well-organized와 병렬을 이루어야 하므로 'it presented the data clearly'(절) 대신 형용사 'clearly presented'나 'clear'가 되어야 합니다. 정확히는 'clearly presented'(형용사 역할 분사)로 고쳐야 합니다.",
    trap: "문장 구조만 보면 이상해 보이지 않지만, 앞의 두 형용사와 절(it presented ~)이 병렬로 연결되어 형태가 불일치합니다.",
    difficulty: "고급",
    subType: "형용사 vs 절 병렬구조 오류",
    discriminationPower: "상",
    commonMistake: "형용사와 절이 병렬될 수 있다고 착각해 오류를 인식하지 못함",
    relatedPart: ["관계사", "분사구문"],
    studyDays: 4,
  },
]
